name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      # - name: Deploy preview bundle for testing
      #   run: yarn deploy
      #  env:
      #    GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
      #    GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          # This will only run when it's a release commit by the changeset bot
          publish: yarn deploy:full
          title: Release latest to Production
        env:
          GITHUB_TOKEN: ${{ secrets.SAJARI_CI_GITHUB_TOKEN }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      - id: deploytostaging
        name: Deploy to Staging
        if: steps.changesets.outputs.published == 'false'
        run: yarn deploy:staging

      - name: 'Slack notification on build failure'
        if: failure() && steps.changesets.outputs.published == 'true'
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BUILD_BREAKAGES_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: '#build-breakages'
          message: ':octagonal_sign: search-widgets production deploy failed | <{{workflowRunUrl}}'

      - name: 'Slack notification on build production success'
        if: success() && steps.changesets.outputs.published == 'true'
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENTS_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          message: ':mag: new search-widgets deployed to production | <{{workflowRunUrl}}>'
